name: flutter_movies_app
description: A sample Flutter app that shows a list of upcoming movies.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  cached_network_image: ^3.2.3
  dio: ^5.1.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^3.1.0
  infinite_scroll_pagination: ^5.1.1
  intl: ^0.20.2
  json_annotation: ^4.8.0
  logger: ^2.0.1
  path: ^1.8.2
  path_provider: ^2.0.14
  provider: ^6.0.5
  shared_preferences: ^2.1.0
  sqflite: ^2.2.6

dev_dependencies:
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter
  freezed: ^3.2.4
  json_serializable: ^6.6.1
  lint: ^2.0.1
  mocktail: ^1.0.4

flutter:
  uses-material-design: true
  assets:
    - assets/config/
